apiVersion: v1
kind: Service
metadata:
  name: bitcoin-core
  namespace: bitcoin
spec:
  selector:
    app: bitcoin-core
  type: NodePort
  ports:
    - name: rpc
      protocol: TCP
      port: 8332
      nodePort: 30332
      targetPort: 8332
    - name: p2p
      protocol: TCP
      port: 8333
      nodePort: 30333
      targetPort: 8333
